import 'dart:convert';

class product {
  List<HeaderCategory>? headerCategory;
  List<MainCategory>? mainCategory;
  List<Popular>? popular;
  List<SeasonsTopPick>? seasonsTopPick;
  List<Sponsored>? sponsored;
  List<HealthWellness>? healthWellness;
  List<InDemand>? inDemand;
  List<WildestCollection>? wildestCollection;

  product(
      {this.headerCategory,
      this.mainCategory,
      this.popular,
      this.seasonsTopPick,
      this.sponsored,
      this.healthWellness,
      this.inDemand,
      this.wildestCollection});

  product.fromJson(Map<String, dynamic> json) {
    if (json['header-category'] != null) {
      headerCategory = <HeaderCategory>[];
      json['header-category'].forEach((v) {
        headerCategory!.add(new HeaderCategory.fromJson(v));
      });
    }
    if (json['main-category'] != null) {
      mainCategory = <MainCategory>[];
      json['main-category'].forEach((v) {
        mainCategory!.add(new MainCategory.fromJson(v));
      });
    }
    if (json['popular'] != null) {
      popular = <Popular>[];
      json['popular'].forEach((v) {
        popular!.add(new Popular.fromJson(v));
      });
    }
    if (json['seasons-top-pick'] != null) {
      seasonsTopPick = <SeasonsTopPick>[];
      json['seasons-top-pick'].forEach((v) {
        seasonsTopPick!.add(new SeasonsTopPick.fromJson(v));
      });
    }
    if (json['sponsored'] != null) {
      sponsored = <Sponsored>[];
      json['sponsored'].forEach((v) {
        sponsored!.add(new Sponsored.fromJson(v));
      });
    }
    if (json['Health-Wellness'] != null) {
      healthWellness = <HealthWellness>[];
      json['Health-Wellness'].forEach((v) {
        healthWellness!.add(new HealthWellness.fromJson(v));
      });
    }
    if (json['InDemand'] != null) {
      inDemand = <InDemand>[];
      json['InDemand'].forEach((v) {
        inDemand!.add(new InDemand.fromJson(v));
      });
    }
    if (json['wildest-collection'] != null) {
      wildestCollection = <WildestCollection>[];
      json['wildest-collection'].forEach((v) {
        wildestCollection!.add(new WildestCollection.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.headerCategory != null) {
      data['header-category'] =
          this.headerCategory!.map((v) => v.toJson()).toList();
    }
    if (this.mainCategory != null) {
      data['main-category'] =
          this.mainCategory!.map((v) => v.toJson()).toList();
    }
    if (this.popular != null) {
      data['popular'] = this.popular!.map((v) => v.toJson()).toList();
    }
    if (this.seasonsTopPick != null) {
      data['seasons-top-pick'] =
          this.seasonsTopPick!.map((v) => v.toJson()).toList();
    }
    if (this.sponsored != null) {
      data['sponsored'] = this.sponsored!.map((v) => v.toJson()).toList();
    }
    if (this.healthWellness != null) {
      data['Health-Wellness'] =
          this.healthWellness!.map((v) => v.toJson()).toList();
    }
    if (this.inDemand != null) {
      data['InDemand'] = this.inDemand!.map((v) => v.toJson()).toList();
    }
    if (this.wildestCollection != null) {
      data['wildest-collection'] =
          this.wildestCollection!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class HeaderCategory {
  String? id;
  String? categoryName;
  String? imageUrl;

  HeaderCategory({this.id, this.categoryName, this.imageUrl});

  HeaderCategory.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    categoryName = json['category-name'];
    imageUrl = json['image-Url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['category-name'] = this.categoryName;
    data['image-Url'] = this.imageUrl;
    return data;
  }
}

class Popular {
  String? id;
  String? productName;
  String? price;
  String? imageUrl;

  Popular({this.id, this.productName, this.price, this.imageUrl});

  Popular.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    productName = json['productName'];
    price = json['price'];
    imageUrl = json['image-url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['productName'] = this.productName;
    data['price'] = this.price;
    data['image-url'] = this.imageUrl;
    return data;
  }
}

class MainCategory {
  String? id;
  String? categoryName;
  String? imageUrl;

  MainCategory({this.id, this.categoryName, this.imageUrl});

  factory MainCategory.fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
      Map<String, dynamic> data) {
    return MainCategory(
      id: data['id'] as String?,
      categoryName: data['category-name'] as String?,
      imageUrl: data['image-Url'] as String?,
    );
  }

  Map<String, dynamic>
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng() {
    return {
      'id': id,
      'category-name': categoryName,
      'image-Url': imageUrl,
    };
  }

  /// `dart:convert`
  ///
  /// Parses the string and returns the resulting Json object as [MainCategory].
  factory MainCategory.fromJson(String data) {
    return MainCategory
        .fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
            json.decode(data) as Map<String, dynamic>);
  }

  /// `dart:convert`
  ///
  /// Converts [MainCategory] to a JSON string.
  String toJson() => json.encode(
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng());
}

class SeasonsTopPick {
  String? id;
  String? productName;
  String? price;
  String? imageUrl;

  SeasonsTopPick({this.id, this.productName, this.price, this.imageUrl});

  factory SeasonsTopPick.fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
      Map<String, dynamic> data) {
    return SeasonsTopPick(
      id: data['id'] as String?,
      productName: data['productName'] as String?,
      price: data['price'] as String?,
      imageUrl: data['image-url'] as String?,
    );
  }

  Map<String, dynamic>
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng() {
    return {
      'id': id,
      'productName': productName,
      'price': price,
      'image-url': imageUrl,
    };
  }

  /// `dart:convert`
  ///
  /// Parses the string and returns the resulting Json object as [SeasonsTopPick].
  factory SeasonsTopPick.fromJson(String data) {
    return SeasonsTopPick
        .fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
            json.decode(data) as Map<String, dynamic>);
  }

  /// `dart:convert`
  ///
  /// Converts [SeasonsTopPick] to a JSON string.
  String toJson() => json.encode(
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng());
}

class WildestCollection {
  String? id;
  String? productName;
  String? price;
  String? imageUrl;

  WildestCollection({this.id, this.productName, this.price, this.imageUrl});

  factory WildestCollection.fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
      Map<String, dynamic> data) {
    return WildestCollection(
      id: data['id'] as String?,
      productName: data['productName'] as String?,
      price: data['price'] as String?,
      imageUrl: data['image-url'] as String?,
    );
  }

  Map<String, dynamic>
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng() {
    return {
      'id': id,
      'productName': productName,
      'price': price,
      'image-url': imageUrl,
    };
  }

  /// `dart:convert`
  ///
  /// Parses the string and returns the resulting Json object as [WildestCollection].
  factory WildestCollection.fromJson(String data) {
    return WildestCollection
        .fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
            json.decode(data) as Map<String, dynamic>);
  }

  /// `dart:convert`
  ///
  /// Converts [WildestCollection] to a JSON string.
  String toJson() => json.encode(
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng());
}

class InDemand {
  String? id;
  String? productName;
  String? price;
  String? imageUrl;

  InDemand({this.id, this.productName, this.price, this.imageUrl});

  factory InDemand.fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
      Map<String, dynamic> data) {
    return InDemand(
      id: data['id'] as String?,
      productName: data['productName'] as String?,
      price: data['price'] as String?,
      imageUrl: data['image-url'] as String?,
    );
  }

  Map<String, dynamic>
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng() {
    return {
      'id': id,
      'productName': productName,
      'price': price,
      'image-url': imageUrl,
    };
  }

  /// `dart:convert`
  ///
  /// Parses the string and returns the resulting Json object as [InDemand].
  factory InDemand.fromJson(String data) {
    return InDemand
        .fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
            json.decode(data) as Map<String, dynamic>);
  }

  /// `dart:convert`
  ///
  /// Converts [InDemand] to a JSON string.
  String toJson() => json.encode(
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng());
}

class HealthWellness {
  String? id;
  String? productName;
  String? price;
  String? imageUrl;

  HealthWellness({this.id, this.productName, this.price, this.imageUrl});

  factory HealthWellness.fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
      Map<String, dynamic> data) {
    return HealthWellness(
      id: data['id'] as String?,
      productName: data['productName'] as String?,
      price: data['price'] as String?,
      imageUrl: data['image-url'] as String?,
    );
  }

  Map<String, dynamic>
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng() {
    return {
      'id': id,
      'productName': productName,
      'price': price,
      'image-url': imageUrl,
    };
  }

  /// `dart:convert`
  ///
  /// Parses the string and returns the resulting Json object as [HealthWellness].
  factory HealthWellness.fromJson(String data) {
    return HealthWellness
        .fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
            json.decode(data) as Map<String, dynamic>);
  }

  /// `dart:convert`
  ///
  /// Converts [HealthWellness] to a JSON string.
  String toJson() => json.encode(
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng());
}

class Sponsored {
  String? id;
  String? productName;
  String? price;
  String? imageUrl;

  Sponsored({this.id, this.productName, this.price, this.imageUrl});

  factory Sponsored.fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
      Map<String, dynamic> data) {
    return Sponsored(
      id: data['id'] as String?,
      productName: data['productName'] as String?,
      price: data['price'] as String?,
      imageUrl: data['image-url'] as String?,
    );
  }

  Map<String, dynamic>
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng() {
    return {
      'id': id,
      'productName': productName,
      'price': price,
      'image-url': imageUrl,
    };
  }

  /// `dart:convert`
  ///
  /// Parses the string and returns the resulting Json object as [Sponsored].
  factory Sponsored.fromJson(String data) {
    return Sponsored
        .fromHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng(
            json.decode(data) as Map<String, dynamic>);
  }

  /// `dart:convert`
  ///
  /// Converts [Sponsored] to a JSON string.
  String toJson() => json.encode(
      toHeaderCategoryId1CategoryNameRechargeImageUrlAssetsImagesRechargePngId2CategoryNameTravelImageUrlAssetsImagesTravelPngId3CategoryNameTwoWheelerImageUrlAssetsImagesTwowheelersPngId4CategoryNamePersonalLoansImageUrlAssetsImagesPersonalloansPngId5CategoryNameInsuranceImageUrlAssetsImagesInsurancePngId6CategoryNameMedicineImageUrlAssetsImagesMedicinePngId7CategoryNamePhoneCashImageUrlAssetsImagesPhonecashPngMainCategoryId1CategoryNameFashionImageUrlAssetsImagesFashionPngId2CategoryNameMobilesImageUrlAssetsImagesMobilephonesPngId3CategoryNameSmartGadgetsImageUrlAssetsImagesWatchPngId4CategoryNameElectronicsImageUrlAssetsImagesElectronicsPngId5CategoryNameHomeEssentialsImageUrlAssetsImagesHomeessentialsPngId6CategoryNameBeautyGroomingImageUrlAssetsImagesBeautygroomingPngId7CategoryNameAppliancesImageUrlAssetsImagesAppliancesPngId8CategoryNameToysBabyImageUrlAssetsImagesToysPngId9CategoryNameSportsFitnessImageUrlAssetsImagesSportsPngId10CategoryNameAutoAccessoriesImageUrlAssetsImagesAutoPngId11CategoryNameFoodHealthcareImageUrlAssetsImagesFoodPngId12CategoryNameFurnitureImageUrlAssetsImagesFurniturePngPopularId1ProductNameFastTrackRevolltPriceJust1799ImageUrlAssetsImagesWatchPngId2ProductNameEnergySavingFansPriceFrom1899ImageUrlAssetsImagesFansPngId3ProductNameGentleCarePriceUpto60OffImageUrlAssetsImagesBeautyproductsPngSeasonsTopPickId1ProductNameMenSTShirtsPriceMin50OffImageUrlAssetsImagesTshirtPngId2ProductNameTrackSuitPriceMin50OffImageUrlAssetsImagesTracksuitPngId3ProductNameMenSShirtPriceMin50OffImageUrlAssetsImagesShirtPngId4ProductNameWatchStrapPriceMin50OffImageUrlAssetsImagesWatchstrapPngSponsoredId1ProductNameNanoPowerbankPriceSplPrice1299ImageUrlAssetsImagesPowerbankPngId2ProductName183BtCallingPriceJust1199ImageUrlAssetsImagesBtcallingPngId3ProductNameEncQuadMicPriceJust899ImageUrlAssetsImagesQuadmicPngId4ProductNameRuggesSneakerPriceMin50OffImageUrlAssetsImagesRuggedsnearkerPngId5ProductNameJawDroppingDealPriceUpto70OffImageUrlAssetsImagesDropdealPngId6ProductNameOutdoorShoesPriceMin30OffImageUrlAssetsImagesOutdoorshowsPngHealthWellnessId1ProductNameMenShoesPriceMin70OffImageUrlAssetsImagesMenslipperPngId4ProductNameMenSlippersPriceMin70OffImageUrlAssetsImagesSlipperPngId3ProductNameDryFruitsPriceMin50OffImageUrlAssetsImagesDryfruitsPngId4ProductNameMouthWashPriceMin30OffImageUrlAssetsImagesMouthwashPngInDemandId1ProductNameGownPriceUpto70OffImageUrlAssetsImagesGownPngId2ProductNameWddingSareesPriceUnder499ImageUrlAssetsImagesWeddingdressPngId3ProductNameEthnicWearPriceFrom199ImageUrlAssetsImagesEthnicswearPngId4ProductNameGrabOrGonePriceUnder799ImageUrlAssetsImagesGrabPngWildestCollectionId1ProductNameKitchenPriceSpecialOfferImageUrlAssetsImagesKitchenPngId2ProductNamePrintedSareesPriceUnder399ImageUrlAssetsImagesPrinteddressPngId3ProductNameTrendyKurtisPriceFrom199ImageUrlAssetsImagesTrendykurtisPngId4ProductNameTrendyKurtisPriceUnder799ImageUrlAssetsImagesTrendykurtisPng());
}
